version: '3.5'
services:
  proxy:
    container_name: proxy
    image: golang:1.12.8
    volumes: 
      - ./service/proxy/:/go/src/proxy
    working_dir: /go/src/proxy
    command: >
      sh -c "go run main.go"
    ports:
      - '443:443'